language: go

go:
    - "1.10"
    - tip

before_install:

script:
    - go test 
#    - $HOME/gopath/bin/goveralls -coverprofile=coverage.cov -service=travis-ci
#    - bash <(curl -s https://codecov.io/bash)
    # - go test -bench=. -benchmem .
    #- sh ./install_all_cmd.sh
